CREATE TABLE IF NOT EXISTS results_site_a.sofa_assumptions (
    person_id BIGINT,
    visit_occurrence_id BIGINT,
    charttime TIMESTAMP,
    resp_sofa INTEGER,
    cardio_sofa INTEGER,
    neuro_sofa INTEGER,
    renal_sofa INTEGER,
    hepatic_sofa INTEGER,
    coag_sofa INTEGER,
    total_sofa INTEGER,
    pf_ratio NUMERIC,
    pao2_value NUMERIC,
    fio2_value NUMERIC,
    fio2_imputed BOOLEAN DEFAULT FALSE,
    fio2_delta_minutes INTEGER,
    map_value NUMERIC,
    nee_total NUMERIC,
    vasopressin_dose NUMERIC,
    vasopressin_included BOOLEAN DEFAULT TRUE,
    gcs_total INTEGER,
    rass_score INTEGER,
    gcs_method VARCHAR(50),
    creatinine_value NUMERIC,
    urine_output_24h NUMERIC,
    rrt_active BOOLEAN,
    bilirubin_value NUMERIC,
    platelets_value NUMERIC,
    ventilation_status BOOLEAN,
    baseline_sofa INTEGER,
    baseline_method VARCHAR(50),
    delta_sofa INTEGER,
    components_scored INTEGER,
    created_at TIMESTAMP DEFAULT NOW()
);